[package]
name = "light_clone_derive"
version = "0.1.0"
edition = "2021"
description = "Derive macro for light_clone crate"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "derive"] }
quote = "1"
proc-macro2 = "1"
